pipeline 
{

agent {
  label 'DevServer'
}

parameters {
  string defaultValue: 'Ravi', name: 'FIRSTNAME'
}

environment{
    NAME = "Lanka"
}

tools {
  maven 'my-maven'
}

stages {
    stage('Build')
    {
            steps {
                sh 'mvn clean package'
                echo "hello $NAME  ${params.FIRSTNAME}"
            }

            
    }

     stage('test')
     {
        parallel {
            stage('testA')
            {
               steps {
                 echo "this is test A"
               }
            }
            stage('testB')
            {
                steps {
                    echo "this is test B"
                }
            }
        }

        post {
            success {
           archiveArtifacts artifacts: '**/target/*.jar'
                    }
                 }

     }
        
    }
}
