pipeline 
{

agent {
  label 'DevServer'
}

parameters {
  string defaultValue: 'Ravi', name: 'FIRSTNAME'
}

environment{
    NAME = "Lanka"
}

tools {
  maven 'my-maven'
}

stages {
    stage('Build') {
            steps {
                sh 'mvn clean package'
                echo "hello $NAME  ${params.LASTNAME}"
            }

            post {
            success {
           archiveArtifacts artifacts: '**/target/*.jar'
                    }
                 }

        }
        
    }
}
