pipeline 
{

agent {
  label 'DevServer'
}


parameters {
  choice choices: ['dev', 'prod'], name: 'select_environment'
}

environment{
    NAME = "Lanka"
}

tools {
  maven 'my-maven'
}

stages {
    stage('Build')
    {
            steps {
                sh 'mvn clean package -DskipTests=true'
            
    }

    stage('test')
     {
        parallel {
            stage('testA')
            {
               agent { label 'DevServer'}
               steps {
                 echo "this is test A"
                 sh "mvn test"
               }
            }
            stage('testB')
            {
                agent { label 'DevServer'}
                steps {
                    echo "this is test B"
                    sh "mvn test"
                }
            }
        }

        post {
            success {
                dir("test-pipeline/target")
                {
                    stash name: "maven-build", includes: "*.jar"
                }
                    }
                 }

     }

        
    }
}
}
